#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 17 17:17:23 MDT 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto cc51a5e303c246b79bdcc2a2cb4f2bc5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot vending_tb_behav xil_defaultlib.vending_tb -log elaborate.log"
xelab -wto cc51a5e303c246b79bdcc2a2cb4f2bc5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot vending_tb_behav xil_defaultlib.vending_tb -log elaborate.log

